apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ip-reverse-app
  namespace: reverseip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ip-reverse-app
  template:
    metadata:
      labels:
        app: flask-ip-reverse-app
    spec:
      containers:
      - name: flask-ip-reverse-app
        image: olatunjym/flask-ip-reverse-app:latest
        ports:
        - containerPort: 5000
